# parameter_simulation
name_of_simulation: 'test'
size_world: [50000, 50000]
resolution: [60, 60]
position_initial: [[0, 0]]
position_target: 'random'
max_belief: 1500
max_runtime: 360000

# parameter_robot
deciding_rate: 1000 #steps/decision
step_distance: 1.5
number_of_directions: 16
path_depth: 1
communication_range_observation: 5000
communication_range_neighbour: 9500
choice_sensor_target: 'angle'

cross_over: 3500
width: 180
smoothness: 6
max_pos: 0.9
#max_neg: 0.1
max_neg: 0.005
std_angle: 3

# parameter_sensor_motion
std_v: 0.001

# parameter_sensor_distance
std_const: 100
std_mean: 0.1

# parameter_belief_position
std_x: 100
std_y: 100

# parameter belief
lower_bound: ''

# parameter_decision
decision: 'lawnmower'
rise_gain: 'on'
#rise_time: 66
rise_time: ''
rise_n: 5
diving_depth: 1